server.port=8081

spring.application.name=order-service

spring.datasource.url=jdbc:h2:mem:orderdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
spring.rabbitmq.addresses=amqp://localhost:5673

clients.payment-service.url=http://localhost:8082

rabbitmq.payment.exchange-request-name=payment-request-exchange
rabbitmq.payment.queue-request-name=payment-request-queue
rabbitmq.payment.exchange-result-name=payment-result-exchange
rabbitmq.payment.queue-result-name=payment-result-queue

resilience4j.retry.instances.paymentServiceRetry.maxAttempts=3
resilience4j.retry.instances.paymentServiceRetry.waitDuration=500ms
resilience4j.retry.instances.paymentServiceRetry.retryExceptions[0]=feign.FeignException
resilience4j.retry.instances.paymentServiceRetry.ignoreExceptions[0]=java.lang.RuntimeException

resilience4j.ratelimiter.instances.paymentClientRateLimiter.limitForPeriod=10
resilience4j.ratelimiter.instances.paymentClientRateLimiter.limitRefreshPeriod=1s
resilience4j.ratelimiter.instances.paymentClientRateLimiter.timeoutDuration=0s

resilience4j.bulkhead.instances.paymentClientBulkhead.maxConcurrentCalls=5
resilience4j.bulkhead.instances.paymentClientBulkhead.maxWaitDuration=0s

resilience4j.circuitbreaker.instances.paymentServiceCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.paymentServiceCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.paymentServiceCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.paymentServiceCircuitBreaker.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.paymentServiceCircuitBreaker.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.paymentServiceCircuitBreaker.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.paymentServiceCircuitBreaker.recordExceptions[0]=feign.FeignException
resilience4j.circuitbreaker.instances.paymentServiceCircuitBreaker.ignoreExceptions[0]=java.lang.RuntimeException

resilience4j.circuitbreaker.instances.orderServiceCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.orderServiceCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.orderServiceCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.orderServiceCircuitBreaker.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.orderServiceCircuitBreaker.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.orderServiceCircuitBreaker.minimumNumberOfCalls=5

logging.level.io.github.resilience4j=DEBUG
