CREATE TABLE IF NOT EXISTS orders (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      customer_id BIGINT NOT NULL,
                                      status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    street VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    postal_code VARCHAR(255) NOT NULL,
    country VARCHAR(255) NOT NULL,
    amount DECIMAL(19,2) NOT NULL,
    currency VARCHAR(3) NOT NULL
    );

CREATE TABLE IF NOT EXISTS order_items (
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           order_id BIGINT NOT NULL,
                                           product_name VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL,
    amount DECIMAL(19,2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    CONSTRAINT fk_order_items_order_id
    FOREIGN KEY (order_id) REFERENCES orders (id)
    ON DELETE CASCADE
    );

CREATE INDEX IF NOT EXISTS idx_order_items_order_id
    ON order_items (order_id);
